api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Dto'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
